### ISSUE TITLE
Multiple domains. 1 host

### ISSUE THREAD

**Issue by RequiDev** [WeebDev/lolisafe#135] opened 2018-07-03 19:59 UTC
In an earlier version it was possible to use 1 host and assign multiple domains to it. (So it returns the proper domain in the upload etc.)

Is that still possible right now, or do I have to code it in by myself?

**Comment by RyoshiKayo** [comment] 2018-07-03 20:01
Yes you can have multiple domains if you're using NGINX. Note that `/dashboard` can only run on one domain as define in the lolisafe config file.

**Comment by RequiDev** [comment] 2018-07-03 20:06
What I mean is, right now if I set the domain in the config to host1 and tell ShareX upload it to host2, it'll still return the domain of host1. I didn't update in like a year and now a lot has changed. Including that.

**Comment by RyoshiKayo** [comment] 2018-07-03 20:07
Yes that will still work for the current release.

Lolisafe will return whatever domain you set in the config.

**Comment by RequiDev** [comment] 2018-07-03 20:08
That's what I mean though. That's not what I want to happen. If I say upload to host2, it should return the url with host2 and not the domain set in the config.

**Comment by Shumatsu** [comment] 2018-07-03 21:05
Trying to comprehend the code and it seems that `processFilesForDisplay` in `uploadController` will always return the domain from config.

**Comment by Pitu** [comment] 2018-07-03 21:19
As of right now, this is not possible to do. Replying with the same host that file was uploaded to, if it's in the hosts array will be possible in the next version, which should come out somewhere between next week.

**Comment by iilukas** [comment] 2018-09-03 02:39
Any update on this feature quite yet?

**Comment by iilukas** [comment] 2018-09-15 19:42
https://github.com/WeebDev/lolisafe/commit/f55e9809b74ce522ff7e2e5fd59effa02447acb5

**Comment by Kosemii** [comment] 2018-09-15 20:29
try it for yourself maybe??

**Comment by iilukas** [comment] 2018-09-15 20:31
@Kosemii This is for anyone that doesn't want to waste there life trying to find the commit hash.

**Comment by alucard0134** [comment] 2018-09-17 02:55
yea this is deep rabbit hole

leave and use some other software

**Comment by Scotxd** [comment] 2018-09-20 11:30
Personally I use two instances of lolisafe running on different ports, and it works just fine.

**Comment by iamluca** [comment] 2018-09-21 01:27
@Scotxd Do you sync the database together as one? I don't want people to have to make multiple accounts you feel me? It's kind of annoying and pointless then. People like the chance and opportunity to use multiple domains for image hosting.

- Luca.

**Comment by iamluca** [comment] 2018-09-21 22:36
@Scotxd Do you have nginx setup, if so what does your setup look like? **Redact** the personal info.

**Comment by Pitu** [comment] 2018-09-21 23:17
Probably same setup as the example one, except n times for each domain if you want to make it easy ¯\_(ツ)_/¯

**Comment by gnosticJade** [comment] 2018-09-21 23:55
Yeah, as Pitu said it's literally just a vhost for each domain pointing to the different port for each lolisafe, to the effect of [this](https://gist.github.com/gnosticJade/5e33c6fdff5f2b41986f097d25a3aef4).

**Comment by Aareksio** [comment] 2018-09-22 10:07
Right now, because of [uploadController.js#L144](https://github.com/WeebDev/lolisafe/blob/master/controllers/uploadController.js#L144), it **always** returns a domain set in `config.domain`. This is what the issue is about. It is **not** nginx101.

**Comment by Kosemii** [comment] 2018-09-22 15:32
Unless you're an idiot, there's no personal info in the nginx config. @iamluca

**Comment by Pitu** [comment] 2018-09-22 16:07
Closing this as the current solution is to run multiple instances of the API pointing to the same database (MySQL, PostgreSQL). I'll try to add better support for it on the next version, but no promises since this solution already works quite well as long as you are not using SQLite.

**Closed by Pitu** 2018-09-22 16:07 UTC
Labels: enhancement

**Comment by Scotxd** [comment] 2018-09-22 17:57
@iamluca Here's my current nginx sites-enabled setup. https://scotf.xyz/Ibpw.png
