### ISSUE TITLE
Option to Strip Image Metadata

### ISSUE THREAD

**Issue by nikhiljha** [WeebDev/lolisafe#137] opened 2018-07-12 00:05 UTC
Imgur/etc automatically remove metadata from images. This is helpful because pictures taken with phones store the location in the image. It would be helpful to have a config option to remove the image metadata.

https://www.npmjs.com/package/exif-stripper

**Comment by Pitu** [comment] 2018-07-12 00:07
Duplicate of #110

**Closed by Pitu** 2018-07-12 00:07 UTC
